{% set name = "mechanize" %}
{% set version = "0.4.10" %}
{% set sha256 = "1dea947f9be7ea0ab610f7bbc4a4e36b45d6bfdfceea29ad3d389a88a1957ddf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - html5lib >=0.999999999

test:
  requires:
    - python {{ python_min }}
  imports:
    - mechanize

about:
  home: https://github.com/python-mechanize/mechanize
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stateful programmatic web browsing.
  description: |
    Stateful programmatic web browsing in Python. Browse pages programmatically with easy HTML form filling and clicking of links.
  dev_url: https://github.com/python-mechanize/mechanize
  doc_url: https://mechanize.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
