{% set name = "mechanize" %}
{% set version = "0.4.6" %}
{% set sha256 = "d16cea241253b5eb6380bf8a46627cad91d1f2c3f93a33279a31ce276d6c5d44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python =2.7|>=3.5
    - pip
    - setuptools
  run:
    - python =2.7|>=3.5
    - html5lib >=0.999999999

test:
  imports:
    - mechanize

about:
  home: https://github.com/python-mechanize/mechanize
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stateful programmatic web browsing.
  description: |
    Stateful programmatic web browsing in Python. Browse pages programmatically with easy HTML form filling and clicking of links.
  dev_url: https://github.com/python-mechanize/mechanize
  doc_url: https://mechanize.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
